export const products = [
  {
    id: '14',
    src: "/homepage/airpulse1.jpeg",
    alt: "Nike Air Pulse 1",
    title: "Nike Air Pulse 1",
    category: "Lifestyle Shoes",
    price: 8995,
    badge: "Popular",
  },
  {
    id: '10',
    src: "/nikeairmax.png",
    alt: "Nike Air Max 270",
    title: "Nike Air Max 270",
    category: "Running Shoes",
    price: 12995,
    badge: "Hot",
  },
  {
    id: '2',
    src: "/snkr/snkr1.jpeg",
    alt: "Nike Air Jordan 1",
    title: "Nike Air Jordan 1",
    category: "Basketball Shoes",
    price: 10995,
    badge: "Best Seller",
  },
  {
    id: '17',
    src: "/snkr/snkr6.jpeg",
    alt: "Nike SB Dunk Low Pro",
    title: "Nike SB Dunk Low Pro",
    category: "Skateboarding Shoes",
    price: 9495,
    badge: "Hot",
  },
  {
    id: '3',
    src: "/snkr/snkr2.jpeg",
    alt: "Nike Air Zoom Pegasus 39",
    title: "Nike Air Zoom Pegasus 39",
    category: "Running Shoes",
    price: 11995,
    badge: "New",
  },
  {
    id: '16',
    src: "/homepage/airpulse3.png",
    alt: "Nike Air Pulse 3",
    title: "Nike Air Pulse 3",
    category: "Lifestyle Shoes",
    price: 10995,
    badge: "Sale",
  },
  {
    id: '7',
    src: "/snkr/snkr6.jpeg",
    alt: "Nike SB Dunk Low",
    title: "Nike SB Dunk Low",
    category: "Skateboarding Shoes",
    price: 8995,
    badge: "Limited",
  },
  {
    id: '8',
    src: "/snkr/snkr7.jpeg",
    alt: "Nike Air Force 1",
    title: "Nike Air Force 1",
    category: "Lifestyle Shoes",
    price: 7995,
    badge: "Popular",
  },
  {
    id: '13',
    src: "/nikezoomx.jpeg",
    alt: "Nike ZoomX Vaporfly",
    title: "Nike ZoomX Vaporfly",
    category: "Running Shoes",
    price: 22995,
    badge: "New",
  },
  {
    id: '9',
    src: "/snkr/snkr8.jpeg",
    alt: "Nike React Infinity Run Flyknit",
    title: "Nike React Infinity Run Flyknit",
    category: "Running Shoes",
    price: 11995,
    badge: "New",
  },
  {
    id: '4',
    src: "/snkr/snkr3.jpeg",
    alt: "Nike Infinity RN 3",
    title: "Nike Infinity RN 3",
    category: "Running Shoes",
    price: 12995,
    badge: "Hot",
  },
  {
    id: '11',
    src: "/nikeairmax90.jpeg",
    alt: "Nike Air Max 90",
    title: "Nike Air Max 90",
    category: "Lifestyle Shoes",
    price: 12995,
    badge: "New",
  },
  {
    id: '6',
    src: "/snkr/snkr5.jpeg",
    alt: "Nike Zoom Fly 5",
    title: "Nike Zoom Fly 5",
    category: "Running Shoes",
    price: 13995,
    badge: "Sale",
  },
  {
    id: '15',
    src: "/homepage/airpulse2.jpeg",
    alt: "Nike Air Pulse 2",
    title: "Nike Air Pulse 2",
    category: "Lifestyle Shoes",
    price: 9995,
    badge: "New",
  },
  {
    id: '5',
    src: "/snkr/snkr4.jpeg",
    alt: "Nike Blazer Mid '77",
    title: "Nike Blazer Mid '77",
    category: "Lifestyle Shoes",
    price: 9995,
    badge: "Trending",
  },
  {
    id: '12',
    src: "/nikeairvapormax.jpeg",
    alt: "Nike Air VaporMax",
    title: "Nike Air VaporMax",
    category: "Running Shoes",
    price: 15995,
    badge: "Limited",
  },
];
